### PR TITLE
create-cert script compatible with windows

### PR DESCRIPTION
**Pull request by styssi**

### CODE REVIEW

**Comment by urre** [comment]
@styssi thanks for adding windows support. But the addition of the drk theme feels out of scope for this?

**Comment by urre** [comment]
@styssi i want to merge this PR, but please remove the theme first

**Comment by styssi** [comment]
My mistake. Didn't mean to push that into the PR :)
Thx for your great work.

by the way here are two explanation videos on youtube on how to setup your repo. One is from me and one from some other guy. In case you are interested in putting that into the readme.md

Linux video: https://www.youtube.com/watch?v=tQBMM1TFcfA&t=6s
Windows video: https://www.youtube.com/watch?v=cEVW5ucNNDY

**Comment by urre** [comment]
@styssi thanks for the contribution! Now merged. Also added some readme instructions for Windows and updated the Changelog.

One question: Can the hardcoded domain myapp.local be removed in the windows scripts?
What i've done in the other cli scripts is that will they read the values in the `./.env` file so you only need to update that.

**Comment by urre** [comment]
@styssi Nice to see the YouTube videos! Happy to see people using my setup. 

Not sure at what time you recorded these, but you can edit the `.env` file to set the domain. Both docker-compose and the cli scripts will read the env values so no manual editing in the scripts is needed.

**Comment by styssi** [comment]
I will give it a try to remove it. I am not an expert in writing scripts :)

**Comment by urre** [comment]
@styssi cool! :) At least there is good instructions now for Windows.

**Comment by urre** [comment]
@styssi But using env is good. I plan to take this setup even further into hosting and more.

**Comment by styssi** [comment]
My plan is to put it on AWS using Kubernetes and the BitBucket pipeline. I do put my Angular/SpringBoot Apps on AWS the same way and that works pretty good.

**Comment by urre** [comment]
Yep. K8s is a good fit for sure.

**Pull request merged**
